### ISSUE TITLE
Tune alert caching

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#16]
Review caching issue where unauthenticated users weren't able to see alerts and outages. Alerts and outages should go live immediately.

**Comment by adamdelaney** [comment]
When an alert node is inserted, updated or deleted we are kicking off purging rules that will purge the node itself as well as /alert page. This does not take into account alerts on the info center or any other path where alerts are shown. Do we need to account for anything other than the node and the alerts page?

**Comment by joewhitsitt** [comment]
Adjustments made to caching seem to be affecting the send email buttons for alerts listed in views. There is a larger issue of making build_info assumptions ( #24  ), but the immediate issue is fixed by removing the cache settings on the views.

Removed cache settings from the following views in PROD:
panel_pane_alerts_major
panel_pane_alerts
alert_major

Need to discuss this more with @adamdelaney before packing up these changes in code.

**Comment by adamdelaney** [comment]
The alert caching issue should be resolved with commit: 83857caef0a775a9fb3f3ab68e81789fb7fce5b7
