### ISSUE TITLE
Format alert digest emails

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#18]
[Daily digest notes (2).docx](https://github.com/ITS-UofIowa/its.uiowa.edu/files/616761/Daily.digest.notes.2.docx)

**Comment by adamdelaney** [comment]
I think a usability study would be helpful.

**Comment by joewhitsitt** [comment]
Now that the usability survey is complete, how should they be formatted and how does #27 fit into it if at all?

**Comment by adriennecoon** [comment]
I've attached the updated example we want to use:
[Daily Digest Example.docx](https://github.com/ITS-UofIowa/its.uiowa.edu/files/666524/Daily.Digest.Example.docx)


•	Change font to Calibri Light
•	All in pt. 11; Header in 14
•	Bold the dates and headers
•	Titles of the alert hyperlinked to its alert page
•	Include start date for all
•	Include times for planned maintenance, not alerts
•	If planned maintenance spans multiple days include start and end date (rare)
•	Separate planned maintenance from outages and degradation of service
•	Display in order of start date, most current (closest to today’s date) displayed first—old notices at the end
•	Add links to main alerts page and calendar view of alerts

**Comment by joewhitsitt** [comment]
I followed these details as close as possible and pushed the changes to DEV. I am going to let DEV do a few test auto cron runs over the weekend to test as I am serving the email a bit differently.

> ...old notices at the end

I separated these out as Ongoing Maintenance since it has a different sort order which could be confused if they were just appended to the planned maintenance list.

Also:

- I am printing the full description for each alert. I didn't see notes about this. Let me know if you want this trimmed.
- [UPDATE] title prefix is printed, but currently not printing the update text/time.
- Multi day with time are printed a bit differently than your mockup to account for the start time on start day and the end time on end day. Dec 24 6:00 AM - Dec 25 10:00 PM

**Comment by joewhitsitt** [comment]
Need to add updates to output. Bulleted list as suggested in  #27

**Comment by joewhitsitt** [comment]
It appears I got some Outlook display issues.

- The Windows Outlook client uses HTML/CSS specs from Internet Explorer 6. Ugh.
- outlook.office.com (office365 web) though better, prefixes class names with x_{original class name} so some styles aren't applied.

I am going to break down and rewrite the output in a HTML 4 table, which seems to be what everyone else does...

**Comment by joewhitsitt** [comment]
Okay. I think I have fixed the output issues with the date: title.
I have tested on windows/mac/web.

still need to include update content.

**Comment by joewhitsitt** [comment]
@adriennecoon I have added the updates to the digest. I pushed it to DEV and switched your address to receive the digest tomorrow morning. Looks roughly like this:
![digest-updates](https://cloud.githubusercontent.com/assets/4663676/22128277/658cf0c8-de65-11e6-9f85-f7a0009ac160.png)
