### ISSUE TITLE
Third tier editors can't delete files 

### ISSUE THREAD

**Issue by adriennecoon** [ITS-UofIowa/its.uiowa.edu#28]
Is this by design? Can we give them access to delete files?

**Comment by joewhitsitt** [comment]
Yes it is by design. We can discuss this further/open up the permission but in the past we have had issues with folks "cleaning up" the site files without understanding the risks. For example, if the file is placed in a wysiwyg area but is deleted first, there is the possibility of the page crashing due to the broken reference. Combine that with the fact that the usage count is not always a true indicator, most developers are setting the permission to allow webmasters to delete files but not editors.

**Comment by adriennecoon** [comment]
Ok that makes perfect sense. Closing out. Closed #28
