### ISSUE TITLE
Add service announcement service category

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#63]
_relates to 1a on requirements document_

- [ ] Audit service announcement functionality. Look for conditional code for the service category vocabulary.
- [ ] Add service announcement term.
- [ ] Update legend block on `/alerts`.
- [ ] Implement service announcement icon.
- [ ] Implement color code for alert calendar at `/alerts/calendar`.
- [ ] Implement service announcement section with collapsible panels on `/alerts` page.
- [ ] Ensure service announcements appear on info center node displays under the IT Service Alerts tab.
- [ ] Verify email functionality works with service announcements.

**Comment by joewhitsitt** [comment]
I've made some assumptions (intertwined with outages/degradation alerts, and color/icon), but otherwise, I believe this is all working.

**Comment by adriennecoon** [comment]
Some changes: 

- Change the display color (on main alerts page and calendar view). Jamie suggests using the same purple we're using for Multiple Issues and then changing the color of multiple issues to "yellow, brown, or grayish". Also, can we keep the same opacity for all of these? 

- Put Service Announcements in its own section under Planned Maintenance

- Rearrange the legend menu to: Operational, Outage, Degradation of Service, Planned Maintenance, Service Announcement, Multiple Issues

**Comment by joewhitsitt** [comment]
@adriennecoon I believe I made the changes you requested. not sure what you meant by opacity, but I attempted to style the collapsible similar to the other alert styles (but purple).

**Comment by adriennecoon** [comment]
@joewhitsitt Here are some edits. It's changed a couple times since I started looking at it, so if you've already accomplished these, just disregard. 

Calendar view: 

- Change the black color for Service Announcement to purple. 

Main alerts view (/alerts): 

- Give Service Announcements it's own section (h2 header like "Current Status" and "Planned Maintenance" alerts). Put this new section below "Current Status" and "Planned Maintenance" sections (right above "Status History")

- Change color of the icon from a black bullseye to a purple bullseye. Change icon color for Multiple Services icon, from purple plus mark to yellow. Do this for both the legend and the Status History section. 

- Change the color of the clickable region that expands/collapses the content from white to purple for Service Announcements.

**Comment by joewhitsitt** [comment]
Sorry, having issues with packaging the code. One sec.

**Comment by joewhitsitt** [comment]
Sorry about that. This is now viewable in DEV.

- [x] Black to purple styling
- [x] Own section under planned maintenance and above service history
- [x] Icon colors (though I used Jaimie's idea of grey for multiple issues)

**Comment by adriennecoon** [comment]
@joewhitsitt Looks good! The only change Jamie wants to make is to the color of the collapsible/expandable clickable banner region (I don't know what to call it). Can that be more of an orange to match the legend icon and the calendar color for Degradation of Service?
