### ISSUE TITLE
Implement GA click tracking on info_center tabs

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#76]
_relates to 9a on requirements document_

Each info center tab should register as a click event in GA.

**Comment by GaryRidgway** [comment]
added in https://github.com/ITS-UofIowa/its.uiowa.edu/pull/83/commits/f31028a7533739453c0fd05b081379f8fd2c716f, but apperently cannot be tested until it is live.

**Comment by joewhitsitt** [comment]
I'd argue that it should send the Node ID instead of the info center name, because if ITS changes the name, you will have a data integrity issue. Of course the the info center name is more readable when looking through GA, but for queries and stuff you don't want an incomplete picture just because the name changed from Skype for Business to Microsoft Teams.

**Comment by joewhitsitt** [comment]
We setup a separate tracking ID for DEV and it appears to be working:
<img width="786" alt="screen shot 2018-01-25 at 12 09 07 pm" src="https://user-images.githubusercontent.com/4663676/35404469-b6c51268-01c8-11e8-8857-b4d1bbcac799.png">

**Comment by adamdelaney** [comment]
Give Adrienne access to the GA for its.dev

**Comment by adriennecoon** [comment]
This works fine. Ok to push to prod.
