### ISSUE TITLE
Missing module themekey

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/its.uiowa.edu#91]
This warning occurs when I sync the production site locally.
```
The following module is missing from the file system: <em      [warning]
class="placeholder">themekey</em>. For information about how to
fix this, see <a href="https://www.drupal.org/node/2487215">the
documentation page</a>. bootstrap.inc:1143
WD features: Attempt to create field field_sn
```

**Comment by joewhitsitt** [comment]
Alan might look into this when he has time.

Traditionally, this has helped: https://www.drupal.org/node/2487215

`drush sql-query "DELETE from system where type = 'module' AND name = 'themekey';"` won't work because I don't think it is in the system table anymore...

`Restore the module and actually disable and uninstall it` hasn't been tried because it was a local to the site module that is no longer in the repo. A possible way to test this without pushing the module all the way back to PROD would be to sync PROD to DEV. Commit the module up to DEV, turn it on/disable/uninstall and then try syncing down to LOCAL. If that works, we should move it back to PROD and try it again there.

**Comment by GaryRidgway** [comment]
I was able to follow this problem with the following steps:

- I sql-sync'd @its.prod to @its.dev
- I downloaded the most recent version of [themekey](https://www.drupal.org/project/themekey)(version 7.x-3.4) to my local site and placed it in to the modules/contrib folder.
- I pushed to dev and ran a `nile @its.dev ceb dev`
- I enabled themekey, ran a `drush @its.dev cc all`, ran a `drush @its.dev rr`, disabled the module, and then uninstalled the module
- then, I ran this string of drush commands `drush @its.dev sqlq "DELETE from system where name = 'themekey_simpletest';" && drush @its.dev sqlq "DELETE from system where name = 'themekey';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_compat';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_css';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_debug';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_example';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_features';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_redirect';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_ui';" && drush @its.dev sqlq "DELETE from system where name = 'themekey_user_profile';" && drush @its.dev sqlq "DELETE from elysia_cron where name = 'themekey_cron';" && drush @its.dev sqlq "TRUNCATE TABLE cache;" && drush @its.dev sqlq "TRUNCATE TABLE cache_bootstrap;"`


After this, sql-syncing from dev had no missing module errors

**Comment by GaryRidgway** [comment]
this has been resolved
